# Generated by Django 4.1.2 on 2022-10-26 21:54

import django.core.validators
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('map_name', models.CharField(choices=[('Dust2', 'Dust2'), ('Overpass', 'Overpass'), ('Train', 'Train'), ('Mirage', 'Mirage')], max_length=255, verbose_name='Mapa')),
                ('quantity', models.IntegerField(default=2, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(2)], verbose_name='Quantidade')),
                ('private', models.BooleanField(default=False, verbose_name='Privada')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
