# Generated by Django 4.1.2 on 2022-10-27 04:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0003_alter_player_room'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='password',
        ),
    ]
