# Generated by Django 4.1.2 on 2022-10-27 04:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match', '0004_remove_player_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='quantity',
            field=models.IntegerField(default=2, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(0)], verbose_name='Quantidade'),
        ),
    ]
